services:
  database:
    image: pgvector/pgvector:pg17
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db_data:/data/db
      - ./01_initial_db.sql:/docker-entrypoint-initdb.d/01_initial_db.sql
      # - ./02_initial_funcs.sql:/docker-entrypoint-initdb.d/02_initial_funcs.sql
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'" ]
      interval: 10s
      timeout: 3s
      retries: 2

  inmemory_db:
    image: redis:latest
    restart: unless-stopped
    env_file: .env
    command: /bin/sh -c "redis-server --requirepass $${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 2
    volumes:
      - inmemory_db_data:/var/lib/redis/data
    ports:
      - ${REDIS_PORT}:6379

  backend:
    restart: unless-stopped
    build:
      context: backend
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - ${BACKEND_PUBLIC_PORT}:${BACKEND_PORT}
    depends_on:
      database:
        condition: service_healthy


  parser:
    build:
      context: backend
      dockerfile: parser.Dockerfile
    depends_on:
      database:
        condition: service_healthy

  keycloak:
    image: quay.io/keycloak/keycloak
    env_file: .env
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USER}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
      KC_DB_USERNAME: ${DB_USERNAME}
      KC_DB_PASSWORD: ${DB_PASSWORD}
      KC_DB_SCHEMA: public
    command:
      start --hostname-strict false --hostname-strict=false --proxy-headers=forwarded --http-enabled=true --import-realm --spi-user-profile-legacy-user-profile-read-only-attributes=*_RES_ACCESS_MODE
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "9000:8080"
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8080/realms/master"]
      start_period: 10s
      interval: 30s
      retries: 3
      timeout: 5s

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    env_file: .env
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_started
      keycloak:
        condition: service_started

volumes:
  db_data:
  inmemory_db_data: